#1st
#Explore different ways to create Numpy arrays?
#Using np.array()

In [1]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [3]:
# Using np.zeros()
arr3 = np.zeros(5)
print(arr3)
arr4 = np.zeros((3, 4))
print(arr4)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
#np.ones()
arr5 = np.ones(4)
print(arr5)
arr6 = np.ones((2, 3))
print(arr6)

[1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
# Using np.arange()
arr7 = np.arange(10)
print(arr7)
arr8 = np.arange(1, 10, 2)
print(arr8)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [9]:
#np.linspace()
arr9 = np.linspace(0, 10, 5)
print(arr9)
arr10 = np.linspace(-1, 1, 4)
print(arr10)

[ 0.   2.5  5.   7.5 10. ]
[-1.         -0.33333333  0.33333333  1.        ]


In [15]:
#np.random
arr11 = np.random.rand(5)
print(arr11)
arr12 = np.random.rand(2, 3)
print(arr12)



#np.random.randn()
arr13 = np.random.randn(5)
print(arr13)
arr14 = np.random.randn(2, 3)
print(arr14)



#np.random.randint()
arr15 = np.random.randint(0, 10, 5)
print(arr15)
arr16 = np.random.randint(1, 100, (3, 4))
print(arr16)

[0.21013759 0.79125678 0.94874756 0.73723808 0.41794195]
[[0.92534347 0.39151856 0.3729093 ]
 [0.37480598 0.48707726 0.66119998]]
[-0.10687297 -0.07868433 -0.00310582 -1.52996739 -0.72827913]
[[ 0.05876259 -0.04758342 -0.87202204]
 [ 0.55462602  1.44933261  1.02915835]]
[3 8 6 0 9]
[[55 74 43 34]
 [86 91 70 29]
 [44 72 57 21]]


In [17]:
# Using np.full()
arr18 = np.full((3, 3), 7)
print(arr18)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [19]:
#Using np.diag()
arr19 = np.diag([1, 2, 3])
print(arr19)
arr20 = np.diag(arr19)
print(arr20)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[1 2 3]


In [21]:
#np.tile()
arr21 = np.tile([1, 2, 3], 3)
print(arr21)
arr22 = np.tile([1, 2, 3], (2, 1))
print(arr22)

[1 2 3 1 2 3 1 2 3]
[[1 2 3]
 [1 2 3]]


In [23]:
#np.fromfunction()
arr23 = np.fromfunction(lambda i, j: i + j, (3, 3))
print(arr23)

[[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]


In [ ]:
#np.genfromtxt() (Reading from Files)
arr24 = np.genfromtxt('data.csv', delimiter=',')
print(arr24)

(GETTING ERROR)("ERROR IS I HAVE NOT (SELECTED THE FILE)OR NOT COPIED THE CSV PATH")

#Manipulate, aggregate and combine arrays
#2nd question
#ARRAY MANIPULATION(RESHAPING ARRAY)

In [10]:
#2nd question
#ARRAY MANIPULATION(RESHAPING ARRAY)
import numpy as np
arr = np.arange(12)
reshaped_arr = arr.reshape((3, 4))
print(reshaped_arr)
flattened_arr = reshaped_arr.flatten()
print(flattened_arr)
raveled_arr = reshaped_arr.ravel()
print(raveled_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [4]:
#Indexing and Slicing
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
slice_arr = arr[1, :]
print(slice_arr)
element = arr[1, 2]
print(element)
arr[0, 0] = 10
print(arr)

[4 5 6]
6
[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [6]:
#Stacking Arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr_vstack = np.vstack((arr1, arr2))
print(arr_vstack)
arr_hstack = np.hstack((arr1, arr2))
print(arr_hstack)
arr_dstack = np.dstack((arr1, arr2))
print(arr_dstack)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[[1 4]
  [2 5]
  [3 6]]]


In [8]:
#(Array Aggregation)mean,median,sum
arr = np.array([1, 2, 3, 4, 5])
total_sum = arr.sum()
print(total_sum)
mean_val = arr.mean()
print(mean_val)
median_val = np.median(arr)
print(median_val)
arr_2d = np.array([[1, 2], [3, 4]])
sum_axis_0 = arr_2d.sum(axis=0)
print(sum_axis_0)
sum_axis_1 = arr_2d.sum(axis=1)
print(sum_axis_1)

15
3.0
3.0
[4 6]
[3 7]


In [10]:
#3(Combining Arrays)
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
stacked_arr = np.stack((arr1, arr2), axis=0)   #(combining with np.stack ())
print(stacked_arr)

[[1 2]
 [3 4]]


In [12]:
#4(Boolean Masking)
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 2
print(mask)
filtered_arr = arr[mask]
print(filtered_arr)

[False False  True  True  True]
[3 4 5]


In [14]:
#5(Set Operations)
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
union_arr = np.union1d(arr1, arr2)
print(union_arr)
intersect_arr = np.intersect1d(arr1, arr2)
print(intersect_arr)
diff_arr = np.setdiff1d(arr1, arr2)
print(diff_arr)

[1 2 3 4 5 6]
[3 4]
[1 2]


#3 question
Apply broadcasting & vectorization techniques?

Apply broadcasting & vectorization techniques?
#Broadcasting in numpy

In [16]:
import numpy as np
arr = np.array([1, 2, 3, 4])
scalar = 10
result = arr + scalar
print(result)

[11 12 13 14]


In [18]:
#Broadcasting with 2D and 1D Arrays
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_1d = np.array([1, 2, 3])
result = arr_2d + arr_1d
print(result)

[[2 4 6]
 [5 7 9]]


In [22]:
# Broadcasting with Mismatched Shapes
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_1d = np.array([1, 2])
result = arr_2d + arr_1d

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [26]:
#2(Vectorization)
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
result = arr1 + arr2
print(result)

[ 6  8 10 12]


In [3]:
#3(Apply broadcasting & vectorization techniques)
import numpy as np
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
arr1d = np.array([10, 20, 30])
result = arr2d * arr1d
print(result)

[[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]


In [5]:
#4(boardcasting with scalar)
import numpy as np
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
result = arr2d + 10
print(result)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [7]:
#5(Broadcasting with Different Shapes)
import numpy as np
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [10, 11, 12]])
arr1d = np.array([1, 2, 3, 4])
result = arr2d * arr1d[:, np.newaxis]
print(result)

[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]
 [40 44 48]]


 #4 question
 Explore Numpy docs and write a blog post?

In [14]:
#1(Efficient Multidimensional Arrays)
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)


#
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [18]:
#2(element wise option)
arr = np.array([1, 2, 3])
result = arr * 2
print(result)


#
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
sum_arr = arr1 + arr2
print(sum_arr)

[2 4 6]
[5 7 9]


In [20]:
#3(Broadcasting)
arr = np.array([1, 2, 3])
result = arr + 10
print(result)

[11 12 13]


In [24]:
#4(Linear Algebra and Matrix Operations)
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.dot(A, B)
print(result)

[[19 22]
 [43 50]]


In [26]:
#5(Random Number Generation)
random_numbers = np.random.rand(3, 2)
print(random_numbers)

[[0.53927676 0.50968425]
 [0.55219542 0.12718843]
 [0.89633274 0.77172826]]


In [28]:
#6(aggregating data)
arr = np.array([1, 2, 3, 4, 5])
mean = np.mean(arr)
print(mean)

3.0
